CREATE OR REPLACE TABLE final_result3(
  source_id STRING,
  subscriber_id STRING,
  first_name STRING,
  middle_name STRING,
  last_name STRING,
  prefix STRING,
  suffix STRING,
  name STRING,
  record_source STRING,
  recorded_ts TIMESTAMP,
  is_verified BOOLEAN,
  Address ARRAY<STRUCT<address_type: STRING, address_line_1: STRING, address_line_2: STRING, city: STRING, state: STRING, ZipCode: STRING, PostalCode: String, country: string>>,
  phones ARRAY<STRUCT<phone: STRING, usage_type: STRING>>,
  email STRING,
  privacy_preference BOOLEAN,
  national_id STRING,
  gender STRING,
  marital_status STRING,
  date_of_birth String,
  year_of_birth STRING,
  deceased_ind BOOLEAN,
  deceased_age INT,
  deceased_date String,
  languages STRUCT<spoken_language_1: STRING, spoken_language_2: STRING>,
  employment STRUCT<first_name: STRING, job_role: STRING, employee_status: STRING, job_hiredate: string>,
  additional_source_value MAP<STRING, STRING>
)