# -*- coding: utf-8 -*-
"""Contact Book Application

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXGQ4wphqmMmas0JLd-yeZKEhVh-HEMO
"""

contacts = []

def add_contact(*args, **kwargs):
    contact = {}
    for arg in args:
        contact[arg] = input(f"Enter {arg}: ")
    contact.update(kwargs)
    contacts.append(contact)
    print("Contact added successfully!")

def view_contacts():
    if not contacts:
        print("Contact book is empty.")
    else:
        for contact in contacts:
            print(contact)

def search_contact():
    search_name = input("Enter the name to search: ")
    search_result = list(filter(lambda x: x["name"].lower() == search_name.lower(), contacts))
    if not search_result:
        print("Contact not found.")
    else:
        print("Search result:")
        print(search_result)

def delete_contact():
    delete_name = input("Enter the name to delete: ")
    global contacts
    contacts = list(filter(lambda x: x["name"].lower() != delete_name.lower(), contacts))
    print("Contact deleted successfully!")

def main_menu():
    while True:
        print("\nContact Book Application")
        print("1. Add a contact")
        print("2. View all contacts")
        print("3. Search for a contact")
        print("4. Delete a contact")
        print("5. Quit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            add_contact("name", "phone", "email")
        elif choice == '2':
            view_contacts()
        elif choice == '3':
            search_contact()
        elif choice == '4':
            delete_contact()
        elif choice == '5':
            print("Exiting Contact Book. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main_menu()